# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='specs_url',
            field=models.CharField(default='dfdfdf', max_length=50),
            preserve_default=False,
        ),
    ]
