# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkbook', '0003_auto_20161216_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='specs_url',
            field=models.CharField(max_length=100),
        ),
    ]
