# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkbook', '0004_auto_20161219_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkcolor',
            name='pantone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
