# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-19 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkbook', '0005_auto_20161219_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default='description here'),
            preserve_default=False,
        ),
    ]
