# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkbook', '0006_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkcolor',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_of_series', to='inkbook.Series'),
        ),
    ]
